
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { GenerationSettings, GenerationStyle } from "../types";

export const generateSpriteSheet = async (
  base64Image: string,
  settings: GenerationSettings
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const styleDescription = {
    [GenerationStyle.CLASSIC_16BIT]: "SNES-style 16-bit pixel art with limited vibrant color palette",
    [GenerationStyle.MODERN_HD]: "High-definition pixel art with smooth shading and detailed textures",
    [GenerationStyle.GAMEBOY]: "4-color monochrome green palette, classic 8-bit handheld aesthetic",
    [GenerationStyle.FANTASY]: "Detailed fantasy pixel art with magical effects and ornate equipment",
    [GenerationStyle.CYBERPUNK]: "Neon-infused pixel art with high contrast and technological details"
  }[settings.style];

  const prompt = `
    ACT AS A PROFESSIONAL GAME ASSET ARTIST SPECIALIZING IN SPRITE SHEETS.
    Task: Convert the attached character image into a professional 2D pixel art sprite sheet.
    
    Character Style: 
    - 2-head tall (Chibi/SD) proportions.
    - Style: ${styleDescription}.
    
    STRICT SPRITE SHEET CONSTRAINTS:
    - **GRID SIZE:** Each individual sprite frame MUST be exactly 32x32 pixels.
    - **ALIGNMENT:** The character MUST be perfectly centered within each 32x32 tile. 
    - **ANCHORING:** Maintain a consistent "feet position" (y-axis ground level) across every single frame in the sheet. This is critical for natural animation without jittering.
    - **PITCH/SCALE:** The character's size should be consistent across all frames (approximately 24-28 pixels tall within the 32x32 box to allow for movement headroom).
    
    Animations Required (One per row, exactly 6 frames per row):
    1. Idle (기본): 6 frames. Character standing, subtle breathing or hair movement.
    2. Walking (걷기): 6 frames. Full walk cycle. Ensure smooth leg transitions.
    3. Attacking (공격): 6 frames. Clear wind-up, impact, and follow-through.
    4. Damaged (피격): 6 frames. Recoil animation.
    5. Death (죽기): 6 frames. Falling down or fading away animation.
    
    Technical Details:
    - Perspective: Top-down 3/4 RPG perspective.
    - Background: ${settings.backgroundColor === 'transparent' ? 'Solid neutral grey' : `Solid ${settings.backgroundColor}`}.
    - NO extra padding between tiles. Tiles must be edge-to-edge in a 6-column by 5-row grid.
    - No text, labels, or UI elements in the final image.
  `;

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png',
              data: base64Image.split(',')[1],
            },
          },
          { text: prompt },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1"
        }
      }
    });

    let imageUrl = '';
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};
